---
defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: scratch_pad_development

test:
  <<: *defaults
  database: scratch_pad_test

production:
  <<: *defaults
  database: scratch_pad_production
  username: username
  password: password
